PreCommit:
  OvercommitConfig:
    enabled: true
    description: Check lab hooks are configured
  EsLint:
    enabled: true
    required_executable: './node_modules/.bin/eslint'
    command: ['./node_modules/.bin/eslint', './src']
  ChangeTogether:
    enabled: true
    description: Check if Nix expressions need to be updated
    files: ['package.json', 'package.nix', 'default.nix']
    message: "run 'rm default.nix && npm2nix package.json package.nix'"
  MochaUnitTest:
    enabled: true
    description: Run unit test

CommitMsg:
  CommitTag:
    enabled: true
    description: Check subject tag
  Imperative:
    enabled: true
    description: Check subject tense
  CapitalizedSubject:
    enabled: false
  SubjectFormat:
    enabled: true
    description: Check subject format

PrePush:
  BranchFormat:
    enabled: true
    description: Check branch naming
